apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
  ports:
    - port: 80
      targetPort: http
